### ISSUE TITLE
Ne fonctionne plus

### ISSUE THREAD

**Issue by smenes** [vvision/yt-auto-dark#6]
Bonjour.

D'abord merci pour cette extension qui nous permet de profiter du magnifique thème sombre de Youtube sans ce connecter.

pour ma part yt-auto-dark ne fonctionne plus depuis 2 jour.

je suis sur Chromium Version 87.0.4280.88 (Build officiel) Arch Linux (64 bits)

mais je crois que le souci viens du menu Youtube.

Des fois le menu reste ouvert  comme ça https://imgur.com/4OH0qXA et le thème change après un moment et des fois le menu ne s'ouvre pas mais je peut y accéder et changer le thème manuellement.

merci encore. bonne continuation.

**Comment by vvision** [comment]
Bonjour.

Merci pour l'info. Je vais voir si j'arrive à reproduire.

Ces dernières semaines Youtube semblait tester une mise nouvelle mise en page, mais seulement sur une fraction des clients web. J'avais eu un ou deux comportements étranges, mais rien de systématique.

**Comment by vvision** [comment]
J'obtiens encore un autre design dans un navigateur de test.
Cette fois, le bouton d'ajout de vidéo a disparu.
<img width="264" alt="image" src="https://user-images.githubusercontent.com/2461851/101390400-0e9ed300-38c3-11eb-9894-b875edb1a4e0.png">

**Comment by smenes** [comment]
oui c'est bizarre. je viens de regarder et le bouton n'était plus la.
j'ai redémarrer le navigateur (il est configuré pour effacer les cookies au redémarrage) et il est réapparut

**Comment by vvision** [comment]
J'ai améliorer le code pour prendre en compte le design avec seulement deux boutons.
Et effectivement, des changements récents du code de l'interface "bloquaient" le processus d'activation du thème sombre jusqu'à expiration du timeout et déclenchement du fallback.

J'ai pu faire un ou deux tests avec les deux designs, puis avec un seul des deux seulement.
Une nouvelle version est en attente de vérification et sera bientôt disponible.
Nous verrons si ça améliore les choses.

**Comment by smenes** [comment]
merci

beau boulot, ça fonctionne bien à nouveau

**Comment by vvision** [comment]
Génial !

Merci d'avoir signaler les dysfonctionnements.
